name: 'Bundle comparison'
description: 'Compare the bundle size between the base branch and the current branch'
inputs:
  current-stats-json-path:
    description: 'The path to the current stats.json file'
    required: true
  base-stats-json-path:
    description: 'The path to the base stats.json file'
    required: true
  github-token:
    description: 'The Github token'
    required: true
  title:
    description: 'An optional addition to the title, which also helps key comments, useful if running more than 1 copy of this action'
    required: false
  describe-assets:
    description: 'Option for asset description output. One of "all" (default), "changed-only", or "none".'
    required: false
    default: 'all'

runs:
  using: 'node16'
  main: 'dist/index.js'
